// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const followerRead = `-- name: FollowerRead :many
SELECT id, name, email FROM users AS OF SYSTEM TIME follower_read_timestamp() WHERE name = $1
`

func (q *Queries) FollowerRead(ctx context.Context, name string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, followerRead, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const followerReadInterval = `-- name: FollowerReadInterval :many
SELECT id, name, email FROM users AS OF SYSTEM TIME '-10s'
`

func (q *Queries) FollowerReadInterval(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, followerReadInterval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noFullScan = `-- name: NoFullScan :many
SELECT id, name FROM users@{NO_FULL_SCAN} WHERE name = $1
`

type NoFullScanRow struct {
	ID   int64
	Name string
}

func (q *Queries) NoFullScan(ctx context.Context, name string) ([]NoFullScanRow, error) {
	rows, err := q.db.QueryContext(ctx, noFullScan, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoFullScanRow
	for rows.Next() {
		var i NoFullScanRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByNameForceIndex = `-- name: UsersByNameForceIndex :many
SELECT id, name, email FROM users@{FORCE_INDEX=users_name_idx} WHERE name = $1
`

func (q *Queries) UsersByNameForceIndex(ctx context.Context, name string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, usersByNameForceIndex, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByPrimary = `-- name: UsersByPrimary :one
SELECT id, name, email FROM users@users_pkey WHERE id = $1
`

func (q *Queries) UsersByPrimary(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, usersByPrimary, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
